"use client"

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'pt' | 'en'

interface LanguageContextType {
  language: Language
  toggleLanguage: () => void
  t: (key: string, params?: Record<string, string>) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Traduções
const translations = {
  pt: {
    // App
    'app.title': 'Ustore',
    'app.subtitle': 'Gerenciamento de Equipes',
    
    // Header/Navigation
    'nav.teams': 'Equipes',
    'nav.tasks': 'Tarefas',
    'nav.analytics': 'Análises',
    'nav.reports': 'Relatórios',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configurações',
    'nav.logout': 'Sair',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Bem-vindo',
    'dashboard.welcome_back': 'Bem-vindo de volta',
    'dashboard.team_overview': 'Aqui está o que está acontecendo com sua equipe hoje.',
    'dashboard.overview': 'Visão Geral',
    'dashboard.recent_activity': 'Atividade Recente',
    'dashboard.stats': 'Estatísticas',
    'dashboard.stats.total_members': 'Total de Membros da Equipe',
    'dashboard.stats.active_tasks': 'Tarefas Ativas',
    'dashboard.stats.pending_reviews': 'Revisões Pendentes',
    'dashboard.stats.team_performance': 'Performance da Equipe',
    'dashboard.stats.members_registered': 'Membros cadastrados',
    'dashboard.stats.not_completed': 'Não concluídas',
    'dashboard.stats.awaiting_approval': 'Aguardando aprovação',
    'dashboard.stats.completion_rate': 'Taxa de conclusão',
'dashboard.recent_activity': 'Atividade Recente',
    'dashboard.recent_activity.title': 'Atividade Recente',
    'dashboard.recent_activity.task_badge': 'Tarefa',
    'dashboard.recent_activity.created_task': 'criou a tarefa',
    'dashboard.recent_activity.completed_task': 'concluiu a tarefa',
    
    // Tasks
    'tasks.title': 'Tarefas',
    'tasks.management_title': 'Gerenciamento de Tarefas',
    'tasks.management_subtitle': 'Crie, atribua e acompanhe tarefas em sua equipe.',
    'tasks.create': 'Criar Tarefa',
    'tasks.edit': 'Editar Tarefa',
    'tasks.delete': 'Excluir Tarefa',
    'tasks.status.todo': 'A Fazer',
    'tasks.status.in_progress': 'Em Progresso',
    'tasks.status.review': 'Revisão',
    'tasks.status.done': 'Concluído',
    'tasks.priority.low': 'Baixa',
    'tasks.priority.medium': 'Média',
    'tasks.priority.high': 'Alta',
    'tasks.priority.urgent': 'Urgente',
    'tasks.loading': 'Carregando tarefas...',
    'tasks.fetch_error': 'Falha ao buscar tarefas:',
    'tasks.update_error': 'Falha ao atualizar status da tarefa:',
    'tasks.team_members_error': 'Falha ao buscar membros da equipe:',
    'tasks.search_placeholder': 'Buscar tarefas...',
    'tasks.status_filter': 'Status',
    'tasks.priority_filter': 'Prioridade',
    'tasks.assigned_to': 'Atribuído a:',
    'tasks.created_by': 'Criado por:',
    'tasks.due_date': 'Data de vencimento:',
    'tasks.created_at': 'Criado em:',
    'tasks.project': 'Projeto:',
    'tasks.overdue': 'Atrasado',
    
    // Projects
    'projects.status.on_track': 'Em dia',
    'projects.status.at_risk': 'Em risco',
    'projects.status.delayed': 'Atrasado',
    'tasks.comments': 'Comentários',
    'tasks.ai_create_title': 'Criar Tarefa com Inteligência Artificial',
    'tasks.ai_create_description': 'Descreva a tarefa que você quer criar em linguagem natural. A IA irá extrair os detalhes para você.',
    'tasks.ai_create_example': 'Ex: "Criar tarefa para Johan Liebert sobre o novo logo para 10/10/2010, prioridade alta."',
    'tasks.ai_create_placeholder': 'Digite os detalhes da sua tarefa aqui...',
    'tasks.ai_create_generate': 'Gerar Tarefa',
    'tasks.filters.advanced': 'Filtros Avançados',
    'tasks.filters.clear_all': 'Limpar Tudo',
    'tasks.filters.assignee': 'Responsável',
    'tasks.filters.select_assignee': 'Selecione o responsável',
    'tasks.filters.all_assignees': 'Todos os Responsáveis',
    'tasks.filters.department': 'Departamento',
    'tasks.filters.select_department': 'Selecione o departamento',
    'tasks.filters.all_departments': 'Todos os Departamentos',
    'tasks.filters.project': 'Projeto',
    'tasks.filters.select_project': 'Selecione o projeto',
    'tasks.filters.all_projects': 'Todos os Projetos',
    'tasks.filters.due_date_range': 'Intervalo de Datas de Vencimento',
    'tasks.filters.from': 'De',
    'tasks.filters.to': 'Até',
    'tasks.filters.show_overdue': 'Mostrar apenas tarefas atrasadas',
    'tasks.filters.all_priorities': 'Prioridades',
    'tasks.filters.filters': 'Filtros',
    'tasks.detail.status': 'Status',
    'tasks.detail.priority': 'Prioridade',
    'tasks.detail.description': 'Descrição',
    'tasks.detail.add_comment': 'Adicionar um comentário...',
    'tasks.comments_fetch_error': 'Falha ao buscar comentários',
    'tasks.add_comment_error': 'Falha ao adicionar comentário',
    'tasks.add_comment_network_error': 'Erro ao adicionar comentário',
    'tasks.confirm_delete_comment': 'Tem certeza que deseja apagar este comentário?',
    'tasks.delete_comment_error': 'Falha ao deletar comentário',
    'tasks.delete_comment_network_error': 'Erro ao deletar comentário',
    'tasks.update_status_error': 'Falha ao atualizar o status da tarefa',
    'tasks.ai_create_error_generate': 'Falha ao gerar a tarefa.',
    'tasks.ai_create_error_network': 'Erro de rede. Verifique sua conexão e tente novamente.',
    'tasks.ai_create_button': 'Criar com IA',
    'tasks.delete_title': 'Excluir Tarefa',
    'tasks.delete_description': 'Você tem certeza que deseja excluir a tarefa "{title}"? Esta ação não pode ser desfeita.',
    'tasks.delete_error': 'Falha ao excluir a tarefa.',
    'tasks.delete_error_network': 'Erro de rede. Por favor, tente novamente.',
    'tasks.create_title': 'Criar Nova Tarefa',
    'tasks.edit_title': 'Editar Tarefa',
    'tasks.title_label': 'Título da Tarefa',
    'tasks.description_label': 'Descrição',
    'tasks.priority_label': 'Prioridade',
    'tasks.assignee_label': 'Atribuir a',
    'tasks.assignee_placeholder': 'Selecione um membro',
    'tasks.due_date_label': 'Data de Vencimento',
    'tasks.project_label': 'Projeto',
    'tasks.project_placeholder': 'ex: Redesenho do site',
    'tasks.tags_label': 'Tags (separadas por vírgula)',
    'tasks.tags_placeholder': 'ex: frontend, urgente, bug',
    'tasks.cancel_button': 'Cancelar',
    'tasks.create_button': 'Criar Tarefa',
    'tasks.save_changes_button': 'Salvar Alterações',
    
    // Teams
    'teams.title': 'Gerenciamento de Equipes',
    'teams.description': 'Gerencie os membros da sua equipe e suas funções.',
    'teams.members': 'Membros',
    'teams.add_member': 'Adicionar Membro',
    'teams.add_member_title': 'Adicionar Membro da Equipe',
    'teams.add_member_error': 'Falha ao adicionar membro',
    'teams.add_member_btn': 'Adicionar Membro',
    'teams.phone_optional': 'Telefone (Opcional)',
    'teams.edit_member': 'Editar Membro',
    'teams.edit_member_title': 'Editar Membro da Equipe',
    'teams.update_member_error': 'Falha ao atualizar membro',
    'teams.update_member_btn': 'Atualizar Membro',
    'teams.password_placeholder': 'Deixe em branco para não alterar',
    'teams.phone': 'Telefone',
    'teams.status': 'Status',
    'teams.status_active': 'Ativo',
    'teams.status_inactive': 'Inativo',
    'teams.role_member': 'Membro',
    'teams.role_manager': 'Gerente',
    'teams.role_admin': 'Administrador',
    'teams.remove_member': 'Remover Membro',
    'teams.delete_member': 'Excluir Membro',
    'teams.delete_member_title': 'Excluir Membro da Equipe',
    'teams.delete_member_description': 'Você tem certeza que deseja excluir {name}? Esta ação não pode ser desfeita e todas as suas tarefas serão reatribuídas.',
    'teams.delete_member_btn': 'Excluir Membro',
    'teams.delete_member_error': 'Falha ao excluir membro',
    'teams.loading': 'Carregando membros da equipe...',
    'teams.fetch_error': 'Falha ao buscar membros:',
    'teams.no_members': 'Nenhum membro da equipe encontrado com os filtros aplicados.',
    'teams.search_placeholder': 'Pesquisar membros da equipe...',
    'teams.role_filter': 'Cargo',
    'teams.department_filter': 'Departamento',
    'teams.status_filter': 'Status',
    'teams.all_roles': 'Todos',
    'teams.all_departments': 'Todos os Departamentos',
    'teams.all_members': 'Todos os Membros',
    'teams.member': 'Membro da Equipe',
    'teams.select_member': 'Selecionar membro',
    'teams.joined_on': 'Ingressou em',
    'teams.performance_title': 'Desempenho por Departamento',
    'teams.best_performance': 'Melhor Desempenho',
    'teams.completion_rate': 'taxa de conclusão',
    'teams.individual_performance': 'Desempenho Individual',
    'teams.department_members': 'Membros de {department}',
    'teams.all_members_performance': 'Todos os Membros',
    'teams.tasks_completed': 'tarefas',
    'teams.completion_rate_label': 'Taxa de Conclusão',
    
    // Analytics
    'analytics.title': 'Análises',
    'analytics.subtitle': 'Obtenha insights sobre o desempenho da sua equipe e o progresso dos projetos.',
    'analytics.tabs.overview': 'Visão Geral',
    'analytics.tabs.tasks': 'Análise de Tarefas',
    'analytics.tabs.team': 'Desempenho por Departamento',
    'analytics.tabs.projects': 'Progresso dos Projetos',
    'analytics.overview': 'Visão Geral',
    'analytics.loading': 'Carregando análises...',
    'analytics.fetch_error': 'Falha ao buscar estatísticas gerais:',
    'analytics.total_tasks': 'Total de Tarefas',
    'analytics.completion_rate': 'Taxa de Conclusão',
    'analytics.active_members': 'Membros Ativos',
    'analytics.overdue_tasks': 'Tarefas Atrasadas',
    'analytics.created_in_period': 'criadas no período',
    'analytics.completed_on_time': 'concluídas a tempo',
    'analytics.in_filter': 'no filtro',
    'analytics.after_deadline': 'após o prazo',
    'analytics.task_analysis': 'Análise de Tarefas',
    'analytics.task_analysis_loading': 'Carregando análise de tarefas...',
    'analytics.task_analysis_error': 'Falha ao buscar análise de tarefas:',
    'analytics.status_distribution': 'Distribuição por Status',
    'analytics.priority_distribution': 'Distribuição por Prioridade',
    'analytics.completion_trend': 'Tendência de Conclusão de Tarefas',
    'analytics.department_performance': 'Desempenho por Departamento',
    'analytics.quantity': 'Quantidade',
    'analytics.completed': 'Concluídas',
    'analytics.created': 'Criadas',
    'analytics.pending': 'Pendentes',
    'analytics.time_range.7d': '7 dias',
    'analytics.time_range.30d': '30 dias',
    'analytics.time_range.90d': '90 dias',
    
    // Reports
    'reports.title': 'Relatórios',
    'reports.subtitle': 'Exporte dados detalhados sobre o desempenho da sua equipe e projetos.',
    'reports.overview': 'Relatórios',
    'reports.team_performance': 'Desempenho do Departamento',
    'reports.team_performance_desc': 'Visão geral da produtividade da equipe.',
    'reports.task_summary': 'Resumo de Tarefas',
    'reports.task_summary_desc': 'Detalhamento de tarefas por status e prioridade.',
    'reports.individual_performance': 'Desempenho Individual',
    'reports.individual_performance_desc': 'Métricas para um membro específico.',
    'reports.project_status': 'Status dos Projetos',
    'reports.project_status_desc': 'Acompanhe o progresso em todos os projetos.',
    'reports.badge.popular': 'Popular',
    'reports.badge.detailed': 'Detalhado',
    'reports.badge.specific': 'Específico',
    'reports.badge.managerial': 'Gerencial',
    'reports.export_excel': 'Exportar para Excel',
    'reports.generating': 'Gerando...',
    'reports.configuration': 'Configuração de Relatório',
    'reports.configuration_desc': 'Configure filtros para seus relatórios.',
    'reports.date_range': 'Intervalo de Datas',
    
    // Report Excel Headers - Portuguese
    'reports.excel.main_title': 'Relatório do Sistema de Gestão de Equipes',
    'reports.excel.type': 'Tipo',
    'reports.excel.period': 'Período',
    'reports.excel.name': 'Nome',
    'reports.excel.role': 'Cargo',
    'reports.excel.department': 'Departamento',
    'reports.excel.tasks_assigned': 'Tarefas Atribuídas',
    'reports.excel.tasks_completed': 'Tarefas Concluídas',
    'reports.excel.completion_rate': 'Taxa de Conclusão (%)',
    'reports.excel.title': 'Título',
    'reports.excel.status': 'Status',
    'reports.excel.priority': 'Prioridade',
    'reports.excel.assignee': 'Responsável',
    'reports.excel.project': 'Projeto',
    'reports.excel.due_date': 'Data de Vencimento',
    'reports.excel.individual_report': 'Relatório de Desempenho Individual',
    'reports.excel.total_tasks': 'Total de Tarefas',
    'reports.excel.progress': 'Progresso (%)',
    'reports.excel.select_member': 'Por favor, selecione um membro para gerar este relatório.',
    'reports.excel.member_not_found': 'Membro não encontrado',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.update_info': 'Atualize seu nome e foto de perfil.',
    'profile.full_name': 'Nome Completo',
    'profile.email_address': 'Endereço de E-mail',
    'profile.saving': 'Salvando...',
    'profile.save_info': 'Salvar Informações',
    'profile.change_password': 'Alterar Senha',
    'profile.change_password_desc': 'Para alterar sua senha, informe a atual e a nova.',
    'profile.current_password': 'Senha Atual',
    'profile.new_password': 'Nova Senha',
    'profile.changing': 'Alterando...',
    'profile.change_password_btn': 'Alterar Senha',
    'profile.password_min_length': 'A nova senha deve ter pelo menos 6 caracteres.',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.theme': 'Tema',
    'settings.system': 'Sistema',
    'settings.light': 'Claro',
    'settings.dark': 'Escuro',
    'settings.theme_description': 'Escolha a aparência do aplicativo.',
    'settings.system_description': 'O tema do sistema alternará automaticamente entre os modos claro e escuro com base nas configurações do seu dispositivo.',
    
    // Auth
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.login': 'Entrar',
    'auth.login_error': 'Falha no login',
     
     // Common
     'common.cancel': 'Cancelar',
     'common.save': 'Salvar',
     'common.save_changes': 'Salvar Alterações',
     'common.name': 'Nome Completo',
     'common.email': 'Email',
     'common.password': 'Senha',
     'common.new_password': 'Nova Senha (opcional)',
     'common.role': 'Cargo',
     'common.department': 'Departamento',
     'common.select_department': 'Selecione um depto',
     'common.select_member': 'Selecione um membro',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.create': 'Criar',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    
    // Common roles and status
    'common.roles.admin': 'Administrador',
    'common.roles.manager': 'Gerente', 
    'common.roles.member': 'Membro',
    'common.status.active': 'Ativo',
    'common.status.inactive': 'Inativo',
    
    // Language
    'language.portuguese': 'Português',
    'language.english': 'English',
    'language.switch': 'Trocar idioma'
  },
  en: {
    // App
    'app.title': 'Ustore',
    'app.subtitle': 'Team Management',
    
    // Header/Navigation
    'nav.teams': 'Teams',
    'nav.tasks': 'Tasks',
    'nav.analytics': 'Analytics',
    'nav.reports': 'Reports',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.welcome_back': 'Welcome back',
    'dashboard.team_overview': 'Here\'s what\'s happening with your team today.',
    'dashboard.overview': 'Overview',
    'dashboard.recent_activity': 'Recent Activity',
    'dashboard.stats': 'Statistics',
    'dashboard.stats.total_members': 'Total Team Members',
    'dashboard.stats.active_tasks': 'Active Tasks',
    'dashboard.stats.pending_reviews': 'Pending Reviews',
    'dashboard.stats.team_performance': 'Team Performance',
    'dashboard.stats.members_registered': 'Registered members',
    'dashboard.stats.not_completed': 'Not completed',
    'dashboard.stats.awaiting_approval': 'Awaiting approval',
    'dashboard.stats.completion_rate': 'Completion rate',
    'dashboard.recent_activity.title': 'Recent Activity',
    'dashboard.recent_activity.task_badge': 'Task',
    'dashboard.recent_activity.created_task': 'created the task',
    'dashboard.recent_activity.completed_task': 'completed the task',
    
    // Tasks
    'tasks.title': 'Tasks',
    'tasks.management_title': 'Task Management',
    'tasks.management_subtitle': 'Create, assign and track tasks in your team.',
    'tasks.create': 'Create Task',
    'tasks.edit': 'Edit Task',
    'tasks.delete': 'Delete Task',
    'tasks.status.todo': 'To Do',
    'tasks.status.in_progress': 'In Progress',
    'tasks.status.review': 'Review',
    'tasks.status.done': 'Done',
    'tasks.priority.low': 'Low',
    'tasks.priority.medium': 'Medium',
    'tasks.priority.high': 'High',
    'tasks.priority.urgent': 'Urgent',
    'tasks.fetch_members_error': 'Failed to fetch team members:',
    'tasks.create_error': 'Failed to create task.',
    'tasks.create_error_network': 'Network error. Please try again.',
    'tasks.update_error': 'Failed to update task.',
    'tasks.update_error_network': 'Network error. Please try again.',
    'tasks.success_created': 'Task created successfully!',
    'tasks.success_updated': 'Task updated successfully!',
    'tasks.success_deleted': 'Task deleted successfully!',
    'tasks.success_status_updated': 'Task status updated successfully!',
    'tasks.success_comment_added': 'Comment added successfully!',
    'tasks.success_comment_deleted': 'Comment deleted successfully!',
    'tasks.loading': 'Loading tasks...',
    'tasks.fetch_error': 'Failed to fetch tasks:',
    'tasks.update_error': 'Failed to update task status:',
    'tasks.team_members_error': 'Failed to fetch team members:',
    'tasks.search_placeholder': 'Search tasks...',
    'tasks.status_filter': 'Status',
    'tasks.priority_filter': 'Priority',
    'tasks.assigned_to': 'Assigned to:',
    'tasks.created_by': 'Created by:',
    'tasks.due_date': 'Due date:',
    'tasks.created_at': 'Created at:',
    'tasks.project': 'Project:',
    'tasks.overdue': 'Overdue',
    'tasks.comments': 'Comments',
    
    // Projects
    'projects.status.on_track': 'On Track',
    'projects.status.at_risk': 'At Risk',
    'projects.status.delayed': 'Delayed',
    'tasks.ai_create_title': 'Create Task with Artificial Intelligence',
    'tasks.ai_create_description': 'Describe the task you want to create in natural language. AI will extract the details for you.',
    'tasks.ai_create_example': 'Ex: "Create task for Johan Liebert about the new logo for 10/10/2010, high priority."',
    'tasks.ai_create_placeholder': 'Type your task details here...',
    'tasks.ai_create_generate': 'Generate Task',
    'tasks.filters.advanced': 'Advanced Filters',
    'tasks.filters.clear_all': 'Clear All',
    'tasks.filters.assignee': 'Assignee',
    'tasks.filters.select_assignee': 'Select assignee',
    'tasks.filters.all_assignees': 'All Assignees',
    'tasks.filters.department': 'Department',
    'tasks.filters.select_department': 'Select department',
    'tasks.filters.all_departments': 'All Departments',
    'tasks.filters.project': 'Project',
    'tasks.filters.select_project': 'Select project',
    'tasks.filters.all_projects': 'All Projects',
    'tasks.filters.due_date_range': 'Due Date Range',
    'tasks.filters.from': 'From',
    'tasks.filters.to': 'To',
    'tasks.filters.show_overdue': 'Show only overdue tasks',
    'tasks.filters.all_priorities': 'Priorities',
    'tasks.filters.filters': 'Filters',
    'tasks.detail.status': 'Status',
    'tasks.detail.priority': 'Priority',
    'tasks.detail.description': 'Description',
    'tasks.detail.add_comment': 'Add a comment...',
    'tasks.comments_fetch_error': 'Failed to fetch comments',
    'tasks.add_comment_error': 'Failed to add comment',
    'tasks.add_comment_network_error': 'Error adding comment',
    'tasks.confirm_delete_comment': 'Are you sure you want to delete this comment?',
    'tasks.delete_comment_error': 'Failed to delete comment',
    'tasks.delete_comment_network_error': 'Error deleting comment',
    'tasks.update_status_error': 'Failed to update task status',
    'tasks.ai_create_error_generate': 'Failed to generate task.',
    'tasks.ai_create_error_network': 'Network error. Check your connection and try again.',
    'tasks.ai_create_button': 'Create with AI',
    'tasks.delete_title': 'Delete Task',
    'tasks.delete_description': 'Are you sure you want to delete the task "{title}"? This action cannot be undone.',
    'tasks.delete_error': 'Failed to delete task.',
    'tasks.delete_error_network': 'Network error. Please try again.',
    'tasks.create_title': 'Create New Task',
    'tasks.edit_title': 'Edit Task',
    'tasks.title_label': 'Task Title',
    'tasks.description_label': 'Description',
    'tasks.priority_label': 'Priority',
    'tasks.assignee_label': 'Assign to',
    'tasks.assignee_placeholder': 'Select a member',
    'tasks.due_date_label': 'Due Date',
    'tasks.project_label': 'Project',
    'tasks.project_placeholder': 'ex: Website redesign',
    'tasks.tags_label': 'Tags (comma separated)',
    'tasks.tags_placeholder': 'ex: frontend, urgent, bug',
    'tasks.cancel_button': 'Cancel',
    'tasks.create_button': 'Create Task',
    'tasks.save_changes_button': 'Save Changes',
    
    // Teams
    'teams.title': 'Team Management',
    'teams.description': 'Manage your team members and their roles.',
    'teams.members': 'Members',
    'teams.add_member': 'Add Member',
    'teams.add_member_title': 'Add Team Member',
    'teams.add_member_error': 'Failed to add member',
    'teams.add_member_btn': 'Add Member',
    'teams.phone_optional': 'Phone (Optional)',
    'teams.edit_member': 'Edit Member',
    'teams.edit_member_title': 'Edit Team Member',
    'teams.update_member_error': 'Failed to update member',
    'teams.update_member_btn': 'Update Member',
    'teams.password_placeholder': 'Leave blank to keep unchanged',
    'teams.phone': 'Phone',
    'teams.status': 'Status',
    'teams.status_active': 'Active',
    'teams.status_inactive': 'Inactive',
    'teams.role_member': 'Member',
    'teams.role_manager': 'Manager',
    'teams.role_admin': 'Administrator',
    'teams.remove_member': 'Remove Member',
    'teams.delete_member': 'Delete Member',
    'teams.delete_member_title': 'Delete Team Member',
    'teams.delete_member_description': 'Are you sure you want to delete {name}? This action cannot be undone and all their tasks will be reassigned.',
    'teams.delete_member_btn': 'Delete Member',
    'teams.delete_member_error': 'Failed to delete member',
    'teams.loading': 'Loading team members...',
    'teams.fetch_error': 'Failed to fetch members:',
    'teams.no_members': 'No team members found with the applied filters.',
    'teams.search_placeholder': 'Search team members...',
    'teams.role_filter': 'Role',
    'teams.department_filter': 'Department',
    'teams.status_filter': 'Status',
    'teams.all_roles': 'All',
    'teams.all_departments': 'All Departments',
    'teams.all_members': 'All Members',
    'teams.member': 'Team Member',
    'teams.select_member': 'Select member',
    'teams.joined_on': 'Joined on',
    'teams.performance_title': 'Performance by Department',
    'teams.best_performance': 'Best Performance',
    'teams.completion_rate': 'completion rate',
    'teams.individual_performance': 'Individual Performance',
    'teams.department_members': '{department} Members',
    'teams.all_members_performance': 'All Members',
    'teams.tasks_completed': 'tasks',
    'teams.completion_rate_label': 'Completion Rate',
    
    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Get insights about your team performance and project progress.',
    'analytics.tabs.overview': 'Overview',
    'analytics.tabs.tasks': 'Task Analysis',
    'analytics.tabs.team': 'Department Performance',
    'analytics.tabs.projects': 'Project Progress',
    'analytics.overview': 'Overview',
    'analytics.loading': 'Loading analytics...',
    'analytics.fetch_error': 'Failed to fetch general statistics:',
    'analytics.total_tasks': 'Total Tasks',
    'analytics.completion_rate': 'Completion Rate',
    'analytics.active_members': 'Active Members',
    'analytics.overdue_tasks': 'Overdue Tasks',
    'analytics.created_in_period': 'created in period',
    'analytics.completed_on_time': 'completed on time',
    'analytics.in_filter': 'in filter',
    'analytics.after_deadline': 'after deadline',
    'analytics.task_analysis': 'Task Analysis',
    'analytics.task_analysis_loading': 'Loading task analysis...',
    'analytics.task_analysis_error': 'Failed to fetch task analysis:',
    'analytics.status_distribution': 'Status Distribution',
    'analytics.priority_distribution': 'Priority Distribution',
    'analytics.completion_trend': 'Task Completion Trend',
    'analytics.department_performance': 'Department Performance',
    'analytics.quantity': 'Quantity',
    'analytics.completed': 'Completed',
    'analytics.created': 'Created',
    'analytics.pending': 'Pending',
    'analytics.time_range.7d': '7 days',
    'analytics.time_range.30d': '30 days',
    'analytics.time_range.90d': '90 days',
    
    // Reports
    'reports.title': 'Reports',
    'reports.subtitle': 'Export detailed data about your team performance and projects.',
    'reports.overview': 'Reports',
    'reports.team_performance': 'Team Performance',
    'reports.team_performance_desc': 'Overview of team productivity.',
    'reports.task_summary': 'Task Summary',
    'reports.task_summary_desc': 'Task breakdown by status and priority.',
    'reports.individual_performance': 'Individual Performance',
    'reports.individual_performance_desc': 'Metrics for a specific member.',
    'reports.project_status': 'Project Status',
    'reports.project_status_desc': 'Track progress across all projects.',
    'reports.badge.popular': 'Popular',
    'reports.badge.detailed': 'Detailed',
    'reports.badge.specific': 'Specific',
    'reports.badge.managerial': 'Managerial',
    'reports.fetch_members_error': 'Failed to fetch team members:',
    'reports.report': 'report',
    'reports.generate_error': 'Failed to generate report',
    'reports.generate_error_console': 'Error generating report:',
    'reports.generate_retry': 'Failed to generate report. Please try again.',
    'reports.configuration': 'Report Configuration',
    'reports.configuration_desc': 'Configure filters for your reports.',
    'reports.date_range': 'Date Range',
    'reports.select_range': 'Select range',
    'reports.export_excel': 'Export to Excel',
    'reports.generating': 'Generating...',
    
    // Report Excel Headers - English
    'reports.excel.main_title': 'Team Management System Report',
    'reports.excel.type': 'Type',
    'reports.excel.period': 'Period',
    'reports.excel.name': 'Name',
    'reports.excel.role': 'Role',
    'reports.excel.department': 'Department',
    'reports.excel.tasks_assigned': 'Tasks Assigned',
    'reports.excel.tasks_completed': 'Tasks Completed',
    'reports.excel.completion_rate': 'Completion Rate (%)',
    'reports.excel.title': 'Title',
    'reports.excel.status': 'Status',
    'reports.excel.priority': 'Priority',
    'reports.excel.assignee': 'Assignee',
    'reports.excel.project': 'Project',
    'reports.excel.due_date': 'Due Date',
    'reports.excel.individual_report': 'Individual Performance Report',
    'reports.excel.total_tasks': 'Total Tasks',
    'reports.excel.progress': 'Progress (%)',
    'reports.excel.select_member': 'Please select a member to generate this report.',
    'reports.excel.member_not_found': 'Member not found',
    
    // Profile
    'profile.title': 'Profile',
    'profile.update_info': 'Update your name and profile picture.',
    'profile.full_name': 'Full Name',
    'profile.email_address': 'Email Address',
    'profile.saving': 'Saving...',
    'profile.save_info': 'Save Information',
    'profile.change_password': 'Change Password',
    'profile.change_password_desc': 'To change your password, enter your current and new password.',
    'profile.current_password': 'Current Password',
    'profile.new_password': 'New Password',
    'profile.changing': 'Changing...',
    'profile.change_password_btn': 'Change Password',
    'profile.password_min_length': 'New password must be at least 6 characters.',
     'profile.info_updated': 'Information updated successfully!',
     'profile.info_update_error': 'Failed to update information.',
     'profile.network_error': 'Network error. Please try again.',
    
    // Settings
     'settings.title': 'Settings',
     'settings.theme': 'Theme',
     'settings.system': 'System',
     'settings.light': 'Light',
     'settings.dark': 'Dark',
     'settings.theme_description': 'Choose the app appearance.',
     'settings.system_description': 'System theme will automatically switch between light and dark modes based on your device settings.',
    
    // Auth
     'auth.email': 'Email',
     'auth.password': 'Password',
     'auth.login': 'Login',
     'auth.login_error': 'Login failed',
     'auth.network_error': 'Network error. Please try again.',
     
     // Common (additional keys)
     'common.name': 'Full Name',
     'common.email': 'Email',
     'common.password': 'Password',
     'common.new_password': 'New Password (optional)',
     'common.role': 'Role',
     'common.department': 'Department',
     'common.select_department': 'Select a department',
     'common.select_member': 'Select a member',
     'common.save_changes': 'Save Changes',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // Common roles and status
    'common.roles.admin': 'Administrator',
    'common.roles.manager': 'Manager',
    'common.roles.member': 'Member',
    'common.status.active': 'Active',
    'common.status.inactive': 'Inactive',
    
    // Roles (legacy - keeping for compatibility)
    'role.admin': 'Administrator',
    'role.manager': 'Manager',
    'role.member': 'Member',
    
    // Language
    'language.portuguese': 'Português',
    'language.english': 'English',
    'language.switch': 'Switch language'
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('pt')

  // Carregar idioma do localStorage na inicialização
  useEffect(() => {
    const savedLanguage = localStorage.getItem('ustore-language') as Language
    if (savedLanguage && (savedLanguage === 'pt' || savedLanguage === 'en')) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Salvar idioma no localStorage quando mudar
  useEffect(() => {
    localStorage.setItem('ustore-language', language)
  }, [language])

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'pt' ? 'en' : 'pt')
  }

  const t = (key: string, params?: Record<string, string>): string => {
    let text = translations[language][key as keyof typeof translations[typeof language]] || key
    
    // Se há parâmetros, substitui os placeholders
    if (params) {
      Object.keys(params).forEach(param => {
        text = text.replace(new RegExp(`\\{${param}\\}`, 'g'), params[param])
      })
    }
    
    return text
  }

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}